root = "."
testdata_dir = "testdata"
tmp_dir = "/tmp"

[build]
  args_bin = []
  bin = "/tmp/arctic"
  cmd = "make dev OUT=/tmp/arctic"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "blizzard/vendor", "testdata", "avalanche"]
  exclude_file = []
  exclude_regex = ["_test.go", "._.*.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  include_file = ["arctic.yml", ".air.toml", "Makefile"]
  kill_delay = "0s"
  log = "arctic.build-errors.log"
  send_interrupt = true
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = true

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
